### ISSUE TITLE
Correção exercício 0.1.1

### ISSUE THREAD

**Issue by mathiasgheno** [LuizHenrique000/ProjetosDWII#1]
# Correção 
1) Faça uma função que irá receber como parâmetro dois numeros.
2) O primeiro parâmetro irá representar o valor de um boleto e o segundo parâmetro irá representar a quantidade de dias que essa conta está atrasada.
3) Para cada dia atrasado deve ser cobrado uma taxa de 0,033%. A função deve retornar o novo valor do boleto. 

Todos os requisitos foram cumpridos. Parabéns. 🎉 

**Nota:** 10

# Comentários
1) O seu parâmetro `dias` poderia ser mais claro. Por exemplo, `diasAtraso`.
2) Suas variáveis `jurosDiarios`, `jurosTotais` e `novoValor` são valores que nunca mudam após a definição. Você pode fazer uso da _keyword_ `const` nesses casos.  

# Orientações
Siga a numeração estabelecida no [notion](https://www.notion.so/Q-A-7721e47711a34d2fbc2feeb721572a67) para os exercícios. O nome desse exercício deveria ser `0.1.1`.

**Comment by LuizHenrique000** [comment]
# Comentário

Correção feita!
