### ISSUE TITLE
Correção exercicio 0.2.1

### ISSUE THREAD

**Issue by mathiasgheno** [LuizHenrique000/ProjetosDWII#2]
# Correção 
1) Faça a modelagem e definição de uma lista de filmes.
2) Cada filme deve conter pelo menos 3 atributos e pelo menos um deles deve ser um array de string. 

Para o item 2 faltou a atribuição de uma propriedade que seja um array de strings. Exemplo de possíveis valores que podem ser um array de strings: `premios`, `atores`, `generos`, `indicacoes`.

**Nota:** 9

# Comentários

Prefira o uso de aspas simples `' '` para facilitar na diferenciacao futura entre html e js. 

# Orientações
Adicionar uma prop q satisfaça o item 2.

**Comment by LuizHenrique000** [comment]
# Comentários

Feita a correção e adicionada a prop!
